HW1
grobert608/hh-school-2020 pull request #1
Opened 2020-11-26 22:01 UTC by grobert608

hh-school-2020-java-collections-stream hw1

2020-11-28 13:30 UTC, grobert608 reviewed
Остальное норм

2020-11-28 13:30 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task1.java
> +            .sorted(Comparator.comparingInt(person -> personIds.indexOf(person.getId())))
не очень экономично, но зато выглядит красиво 
можно переписать без сортировки, будет работать линейно
```
Map<Integer, Person> idsToPersons = persons.stream()
            .collect(Collectors.toMap(Person::getId, Function.identity()));
return personIds.stream()
            .map(idsToPersons::get)
            .collect(Collectors.toList());
```

2020-11-29 17:33 UTC, genroelgvozo requested changes

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task1.java
> +            .sorted(Comparator.comparingInt(person -> personIds.indexOf(person.getId())))
вот как раз вариант из коммента - норм (и быстро и понятно)
А вот компаратор через индекс - не сказал бы что выглядит красиво)) да и n*n не гуд

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task2.java
> +    return Stream.of(persons1, persons2).flatMap(Collection::stream)
Вопросов нет)

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task3.java
>    private List<Person> sort(Collection<Person> persons) {
Вопросов нет)

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task5.java
> +    return persons.stream().map(person -> Task5.convert(person, personAreaIds.get(person.getId())))
тут можно без указания класса, статический метод из того же класса
А так все гуд

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task6.java
> +    return persons.stream().flatMap(person -> areas.stream()
Получается мы для каждой персоны (которых может быть 1000) перебираем все арейки (которых тоже может быть 1000), хотя у каждой из них только одна-две арейки (ну наверное)
Вот может как-то заранее подготовить данные (например как в первой задаче), чтобы получение имени было быстрым по айди, и тогда можно бежать только по нужным арейкам а не всем

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task7.java
>    private Set<String> vacancyNames(Collection<Company> companies) {
Вопросов нет)

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    // isEmpty() более предпочтительный вариант, лучше скипать в потоке
Можно вообще без проверки, скип не упадет, стримы умные)
а вот вопрос, есть ли принципиальная разница между скип и ремув, чем твой код еще лучше, кроме того что он короче?

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return Set.copyOf(getNames(persons));
а зачем копи? чем конструктор не угодил?)

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return personName.toString();
Ну стало быстрее, но еще более громоздко (разве что ифы однострочные сделал 😄 )
А что если задуматься над стрим апи, ведь оно для обработки данных... Хочется лаконичный код

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, Person::getFirstName));
Это правда лучше, но иногда твой код упадет. Ифчик в оригинальном коде должен был намекнуть

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
А сколько работает изначальный и твой код? От чего зависит? Как сделать чтобы всегда было супер быстро?)

2020-11-29 17:33 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Чем лучше?) Аргументируй, есть принципиальная проблема у исходного кода

2020-11-29 21:00 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return Set.copyOf(getNames(persons));
Хороший тон, если есть возможность создания экземпляра через статический метод, пользоваться возможностью.

2020-11-29 21:08 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    // isEmpty() более предпочтительный вариант, лучше скипать в потоке
Удаляя первый элемент у Листа, мы все коллекцию будем сдвигать в памяти, очень нерациональная затея, а скип от головы пойдет и по времени ничего не потеряем.

2020-11-29 21:19 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
В твоем решение `count` будет каждый раз пересоздаваться при инкрементации, можно избежать, осуществив подсчет терминальной операцией.

2020-11-30 21:03 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task6.java
> +    return persons.stream().flatMap(person -> areas.stream()
Спасибо, исправил

2020-11-30 21:03 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return personName.toString();
Хочется, исправил)

2020-11-30 21:03 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, Person::getFirstName));
Не заметил, исправил

2020-11-30 21:06 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
Оба работают за квадрат, так как проверяют все элементы, круто использовать `!Collections.disjoint()`

2020-12-04 17:08 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    // isEmpty() более предпочтительный вариант, лучше скипать в потоке
Ну хорошо, допустим знаем что там линкед лист)
на самом деле идеологически так делать плохо - менять входные параметры
Пользователь вашей функции такого не ожидает

2020-12-04 17:13 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return Set.copyOf(getNames(persons));
тут ты путаешь котлеты и мухи)
Да, советуют использовать статические билдеры вместо конструкторов, потому что у них есть имя, и оно может что-то говорить (например Person.createEmpty() вместо new Person(), и понятнее что в первом случае происходит чем во втором), так же они могут быть синглтонами, ну и вообще можно скрывать разную логику.

Тут же copyOf во-первых странно идеологически (зачем тут копирование, смысл в чем, заставляет задуматься читающего код, а задумываться тут не над чем, это лишняя трата времени), во-вторых создает неизменяемую коллекцию, что в своем бизнес коде может быть неожиданностью (неизменяемость это и хорошо, но лучше так не делать в своем же коде, иначе ошибок не избежать)

короче  new HashSet<>() понятнее

2020-12-04 17:14 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
оно круто, но если ни одна из коллекция не является хеш сетом, то будет так же медленно (по факту она работает так же как ты написал, только еще выбирает коллекцию к которой anyMatch применить)
Вот может persons2 как-то преобразовать, чтобы было всегда быстро?

2020-12-04 17:17 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Ну да, но хотел услышать что исходный код иногда неправильно считал)
а все потому, что стрим может быть параллельный

2020-12-04 17:21 UTC, genroelgvozo requested changes

2020-12-04 17:21 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task6.java
> +              .map(x -> p.getFirstName() + " - " + x)).collect(Collectors.toSet());
Я вот не очень понял, зачем вторая мапа
Что если тут вместо idPersonToNameAreas подставить изначальную, а вместо + x подставить idAreaToNameAreaMap.get(x) ?)
И в лямбдах надо называть нормально переменные тоже, person и areaId а не p x

2020-12-04 17:21 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return (persons.isEmpty()) ?
Так, не понял, я же написал что можно вообще проверки))
Вот прям совсем без проверки
Все будет работать

2020-12-04 17:21 UTC, genroelgvozo commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, this::convertPersonToString));
тут вроде не поправил, ответил же на мой коммент что не заметил (код будет падать, нужно что-то поправить)

2020-12-04 17:57 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    // isEmpty() более предпочтительный вариант, лучше скипать в потоке
Спасибо

2020-12-04 21:39 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task6.java
> +              .map(x -> p.getFirstName() + " - " + x)).collect(Collectors.toSet());
Ого, действительно! Спасибо

2020-12-04 21:40 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return (persons.isEmpty()) ?
Спасибо, исправил)

2020-12-04 21:45 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return Set.copyOf(getNames(persons));
Спасибо, поправил

2020-12-04 21:50 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
Можно как я написал, но только `persons1.stream().anyMatch(persons2::contains)`

2020-12-04 22:00 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Интерсно, спасибо за комментарий

2020-12-04 22:01 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task1.java
> +            .sorted(Comparator.comparingInt(person -> personIds.indexOf(person.getId())))
Согласен, забыл функцию мера)

2020-12-04 22:04 UTC, grobert608 commented on hh-school-2020-java-collections-stream/src/tasks/Task1.java
> +            .sorted(Comparator.comparingInt(person -> personIds.indexOf(person.getId())))
Согласен, забыл, спасибо

2020-12-08 17:29 UTC, genroelgvozo approved these changes

2020-12-09 13:44 UTC, merged