SQL HW1
grobert608/hh-school-2020 pull request #2
Opened 2020-12-09 13:52 UTC by grobert608

2020-12-11 22:30 UTC, eldmitrieva requested changes

2020-12-11 22:30 UTC, eldmitrieva commented on hh-school-2020-db-sql/hw.sql
> +             THEN compensation_to + compensation_from
тут не хватает деления на 2

2020-12-11 22:30 UTC, eldmitrieva commented on hh-school-2020-db-sql/hw.sql
> +    RIGHT JOIN vacancy ON vacancy.hirer_id = hirer.hirer_id
В таком случае в выборке будут только те работодатели, у которых есть вакансии и отклики, но хотелось бы, чтобы были все. просто если ни у кого нет ни откликов, ни приглашений, в итоговой выборке ничего не будет, а хотелось бы там видеть 5 работодателей с нулями

2020-12-11 22:30 UTC, eldmitrieva commented on hh-school-2020-db-sql/hw.sql
> +    GROUP BY hirer_name, respond.vacancy_id
у тебя нет ограничения, что имя работодателя должно быть уникальным (оно и не нужно, бывают компании с одинаковым названием), поэтому тут ты схлопнешь рабтодателей с одним названием в одного

2020-12-11 22:30 UTC, eldmitrieva commented on hh-school-2020-db-sql/hw.sql
> +GROUP BY hirer.area_id;
стоит добавить пустую строку в конце файла

2020-12-11 22:30 UTC, eldmitrieva commented on hh-school-2020-db-sql/hw.sql
> +       max(respond.time_apply - vacancy.time_apply) AS max_time,
тут должно считаться максимальное время до ПЕРВОГО отклика, надо исправить

2020-12-12 13:29 UTC, grobert608 commented on hh-school-2020-db-sql/hw.sql
> +             THEN compensation_to + compensation_from
Поправил, спасибо

2020-12-12 13:30 UTC, grobert608 commented on hh-school-2020-db-sql/hw.sql
> +    RIGHT JOIN vacancy ON vacancy.hirer_id = hirer.hirer_id
Поправил, проверил, спасибо

2020-12-12 13:30 UTC, grobert608 commented on hh-school-2020-db-sql/hw.sql
> +    GROUP BY hirer_name, respond.vacancy_id
Поправил, проверил, спасибо

2020-12-12 13:30 UTC, grobert608 commented on hh-school-2020-db-sql/hw.sql
> +       max(respond.time_apply - vacancy.time_apply) AS max_time,
Поправил, спасибо

2020-12-20 19:49 UTC, eldmitrieva approved these changes

2020-12-25 16:18 UTC, merged